Switch Unit Testing and CodeSniffing to GitHub Actions
indieweb/wordpress-indieweb pull request #166
Opened 2021-05-30 23:08 UTC by dshanske

Being as Travis CI is no longer a guarantee, switching over to GitHub Actions for unit tests and codesniffing.

2022-05-15 21:39 UTC, tw2113 approved these changes

2022-05-16 05:20 UTC, pfefferle requested changes

2022-05-16 05:20 UTC, pfefferle commented on .github/workflows/phpunit.yml
> +  phpcs:
This should be `phpunit:` otherwise it mixes up the results with the phpcs action.

2022-05-16 05:20 UTC, pfefferle commented on composer.json
> +        "sebastian/phpcpd": "^3.0 || ^5.0 || ^6.0",
Indents!

2022-05-17 05:29 UTC, pfefferle approved these changes
LGTM

2022-05-18 01:03 UTC, merged