Update and simplify plugin structure
indieweb/wordpress-indieweb pull request #267
Opened 2024-11-29 07:43 UTC by pfefferle

2024-11-29 13:37 UTC, dshanske requested changes
The removal of SASS means the rebuild process for the icons is not scripted. The build icons script doesn't generate the final css file.

Probably could come up with a non Grunt solution though.

2024-11-29 13:39 UTC, pfefferle commented
Oooos! I will add an non task instead! Good catch!

2024-11-29 13:50 UTC, dshanske commented
That build process is something I have thought of redoing. SinpleIcons has gotten a lot larger since I picked it and maybe I should be doing a subset.

Just curation is a pain.

2024-12-07 15:49 UTC, dshanske commented
I was thinking about this. I could add sass as a script and dependency to the package.json file and run it that way. Will test.

2025-12-19 15:20 UTC, dshanske approved these changes
This looks good to me.

2025-12-19 16:38 UTC, merged